site_name: QA TechStore

theme:
  name: material
  language: pt-BR

  palette:
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark mode

    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode

nav:
  - Home: index.md
  - Overview: overview.md
  - Requirements: requirements.md
  - QA Strategy: qa-strategy.md
  - API: api.md

extra_css:
  - styles/style.css

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - mermaid2

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js